listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=155.212.128.190
min-port=49160
max-port=49200

fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=REPLACE_WITH_TURN_SECRET
realm=turn.visov.ru
server-name=turn.visov.ru

total-quota=200
bps-capacity=0
stale-nonce=600

cert=/etc/letsencrypt/live/turn.visov.ru/fullchain.pem
pkey=/etc/letsencrypt/live/turn.visov.ru/privkey.pem

no-multicast-peers
no-cli
no-loopback-peers
no-tlsv1
no-tlsv1_1

log-file=stdout
verbose
